In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目  國文   英文   數學   地理  歷史
學號
1   53   81   94   88  68
2   69   80   51   94  53
3   79   72   64   51  70
4   50   97   50   78  93
5   93   61   67   76  88
6   82   60   93   98  86
7   97   70   55   86  89
8   85   80   57   91  95
9   80   77   54  100  89
10  54   87   96   68  66
11  89   63   83   87  68
12  85   57  100   70  61
13  83   81   62   99  53
14  53   91   98   76  62
15  52   81   86   64  95
16  94   73   50   67  92
17  92   90   51  100  98
18  67   94   70   59  76
19  88   96   53   55  77
20  76   55   91   50  99
21  63   58   87   66  89
22  84   92   89   86  77
23  72   55   50   51  83
24  60   55   52   77  89
25  51   65   87   85  96
26  50   56   99   90  83
27  77   87   72   88  56
28  83   72   55   76  66
29  62  100   86   83  72
30  82   85   67   75  51
31  63   75   60   75  57
32  60   80   58   70  93
33  76   89   54   53  93
34  57   78  100   91  77
35  63   94   99   55  84
36  63   51  100   54  57
37  78   77   77   92  50
38  69   51   78   93  81
39  76   94   62   93  99
40  74   67   91   67  79
41  97   92   86   52  90
42  68   53   55   51  61
43  78   61   59   74  67
44  82   88   99   72  98
45  79   50   56   52  88
46  66   62   86   57  75
47  62   78   73   88  54
48  99   72   57   80  98
49  68   92   58   99  50
50  60   60   52   70  58

In [2]:
def call(s):
    min = s.min()
    max = s.max()
    median = s.median()
    return pd.Series([min,max,median],index=['最低分','最高分','中間值'])

scores_pd.apply(call)

科目     國文     英文     數學     地理    歷史
最低分  50.0   50.0   50.0   50.0  50.0
最高分  99.0  100.0  100.0  100.0  99.0
中間值  75.0   77.0   68.5   76.0  78.0